apiVersion: v1
kind: ReplicationController
metadata:
 name: ashu-rc111
spec:
 replicas: 1  # no of pods 
 template: # it will use old yaml data 
  metadata:
   labels:
    x: helloashujsp
  spec:
   containers:
   - image: dockerashu/javaweb:jspv007
     name: ashuc44
     ports:
     - containerPort: 8080