apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sunilpod-aws1
  name: sunilpod-aws1
spec:
  containers:
  - args:
    - yaml
    image: dockerashu/ashuhttpd:febv1
    name: sunilpod-aws1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
